services:
  - type: web
    name: gigachat
    env: python
    buildCommand: pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet'); nltk.download('omw-1.4')" && python scripts/train_model.py
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
