services:
  - type: web
    name: gigachat
    env: python
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader punkt wordnet omw-1.4 && python scripts/train_model.py
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
